function candidate_indices = find_candidate_points( ...
    start_latlon, end_latlon, map_positions, expansion_factor)
%FIND_CANDIDATE_POINTS Select map points in the start-to-end ellipse.
%
% A point is retained when the sum of its distances to the two endpoints is
% less than EXPANSION_FACTOR times the direct endpoint distance.

    if nargin < 4
        expansion_factor = 2;
    end

    distance_from_start = geographic_distance_meters( ...
        map_positions(:, 1), map_positions(:, 2), ...
        start_latlon(1), start_latlon(2));

    distance_from_end = geographic_distance_meters( ...
        map_positions(:, 1), map_positions(:, 2), ...
        end_latlon(1), end_latlon(2));

    endpoint_distance = geographic_distance_meters( ...
        start_latlon(1), start_latlon(2), ...
        end_latlon(1), end_latlon(2));

    candidate_indices = find( ...
        distance_from_start + distance_from_end < ...
        expansion_factor * endpoint_distance);
end
