function latlon = grid_index_to_latlon( ...
    grid_indices, longitude_step, latitude_step, ...
    min_longitude, min_latitude)
%GRID_INDEX_TO_LATLON Convert grid indices to latitude/longitude coordinates.

    latlon = (grid_indices - 1) .* [latitude_step, longitude_step] + ...
        [min_latitude, min_longitude];
end
