function latlon = sionna_grid_index_to_latlon( ...
    grid_indices, longitude_step, latitude_step, ...
    origin_longitude, origin_latitude)
%SIONNA_GRID_INDEX_TO_LATLON Convert Sionna grid indices to coordinates.

    origin_grid_index = [668, 410];
    latlon = (grid_indices - origin_grid_index) .* ...
        [latitude_step, longitude_step] + ...
        [origin_latitude, origin_longitude];
end
